version: '3.2'

services:
  app:
    container_name: ${CONTAINER_PREFIX}_app
    image: $REGISTRY/main/app:$CI_COMMIT_SHA
    command: "tail -f /dev/null"
    volumes:
      - ./:/var/www
    working_dir: /var/www
