stages:
  - build
  - deploy

variables:
  REGISTRY: "registry.gitlab.com/crocos.kz/kaznik"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stage_build:
  stage: build
  tags:
    - build
  only:
    - main
  script:
    - docker build --build-arg NODE_ENV="dev" -t "$REGISTRY/main/app:$CI_COMMIT_SHA" -f ./_docker/gitlab/app/Dockerfile .
    - docker push "$REGISTRY/main/app:$CI_COMMIT_SHA"

stage_deploy:
  stage: deploy
  tags: 
    - docker
  only:
    - main
  script:
    - export CONTAINER_PREFIX=kaznik
    - docker stop $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker rm $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker volume rm $(docker volume ls | grep ${CONTAINER_PREFIX}_ | awk '{print $2}') || true
    - docker-compose -p $CONTAINER_PREFIX -f docker-compose.yml up -d
    - docker exec ${CONTAINER_PREFIX}_app chown -R 997:997 .
    - docker exec ${CONTAINER_PREFIX}_app npm install
    - docker exec ${CONTAINER_PREFIX}_app npm run build
    - docker exec ${CONTAINER_PREFIX}_app pm2 restart kaznik




